### ISSUE TITLE
remove mysql from direct dependencies

### ISSUE THREAD

**Issue by eamonnmag** [inveniosoftware/invenio-ext#28]
If the db is up to the app developer, then including mysql-python as a dependency is a problem since for the build to be successful, mysql needs to be installed on the machine, otherwise you'll get this error. 

```
Collecting MySQL-python>=1.2.5 (from invenio-ext>=0.1.0->invenio-access->hepdata==2.0.0.dev20150000)
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-GSqXWu/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-build-GSqXWu/MySQL-python/setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-build-GSqXWu/MySQL-python/setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
```

**Comment by lnielsen** [comment]
I think you are installing invenio-access without ``--pre`` . Invenio-Ext is deprecated and not used by Invenio 3

**Comment by eamonnmag** [comment]
Ok, great. Didn't realise!
